version: '3.8'

services:
  db:
    container_name: postgresql
    image: postgres:16.1
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  api:
    container_name: backend
    depends_on:
      - db
    build: ./api
    volumes:
      - ./api/:/app
      - /app/node_modules
    ports:
      - 5000:5000
    restart: always

  client:
    container_name: frontend
    build: ./client
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres:
    name: transcendence_postgres

networks:
  transcendence_network:
    name: transcendence_network
